// Per-tool "How to use" steps. One unique 4-step recipe per tool so every
// tool page reads distinctly instead of showing the generic default.
import type { HowToStep } from "@/lib/tool-content";

export const TOOL_HOWTO: Record<string, HowToStep[]> = {
  "merge-pdf": [
    { name: "Add your PDFs", text: "Drag two or more PDF files into the upload zone, or tap Browse to pick them from your device." },
    { name: "Reorder pages", text: "Drag the file thumbnails to arrange the merge order exactly the way you want the final document to read." },
    { name: "Click Merge", text: "Hit the Merge button — CrispPDF stitches every file together inside your browser, keeping fonts and layout intact." },
    { name: "Download the combined PDF", text: "Your merged PDF downloads instantly. No signup, no watermark, and the source files never leave your device." },
  ],
  "split-pdf": [
    { name: "Upload the PDF", text: "Drop the PDF you want to split into the upload box. Thumbnails of every page appear in a grid." },
    { name: "Pick a split mode", text: "Choose ranges (e.g. 1-5, 6-10), split every N pages, or select individual pages to extract." },
    { name: "Run Split", text: "Click Split. CrispPDF cuts the file locally — nothing is uploaded to a server." },
    { name: "Download the parts", text: "Each range downloads as its own PDF, or all parts arrive as a single ZIP." },
  ],
  "compress-pdf": [
    { name: "Upload your PDF", text: "Drag the oversized PDF into the compressor. It reads the file in your browser — no upload." },
    { name: "Pick a target size", text: "Choose a preset (100 KB, 200 KB, 1 MB) or a quality level (High / Medium / Low)." },
    { name: "Compress", text: "Click Compress. Images are re-sampled and unused metadata stripped until the target size is hit." },
    { name: "Download the smaller PDF", text: "The optimised PDF downloads instantly, ready for email, exam forms, or web upload." },
  ],
  "pdf-to-word": [
    { name: "Upload the PDF", text: "Drop the PDF you want to edit into the converter. Scans need OCR first — use the OCR PDF tool." },
    { name: "Start conversion", text: "Click Convert to DOCX. CrispPDF extracts text, tables, and images while preserving paragraph and font styles." },
    { name: "Review layout", text: "Complex multi-column layouts may simplify slightly; single-column resumes and contracts stay near-identical." },
    { name: "Download the .docx", text: "Open the file in Word, Google Docs, or LibreOffice and edit freely." },
  ],
  "pdf-to-excel": [
    { name: "Upload the PDF", text: "Drop a PDF that contains tables — invoices, bank statements, or reports." },
    { name: "Detect tables", text: "CrispPDF scans each page for tabular data and previews the detected rows and columns." },
    { name: "Convert to XLSX", text: "Click Convert. Each page becomes a sheet with cells you can edit and formulas you can add." },
    { name: "Download the spreadsheet", text: "Open the .xlsx in Excel, Google Sheets, or Numbers — no formatting fixes required for clean tables." },
  ],
  "pdf-to-ppt": [
    { name: "Upload the PDF", text: "Drop the PDF you want to turn into a slide deck." },
    { name: "Convert to PPTX", text: "Click Convert. Each PDF page becomes an editable slide with text and images preserved." },
    { name: "Download the deck", text: "Your .pptx downloads and opens cleanly in PowerPoint, Keynote, or Google Slides." },
    { name: "Edit slides", text: "Change text, swap images, and re-theme the deck without starting from scratch." },
  ],
  "pdf-to-jpg": [
    { name: "Upload the PDF", text: "Drop your PDF into the converter. Multi-page files are handled in a single pass." },
    { name: "Pick JPG quality", text: "Choose the DPI (72 for web, 300 for print) and set colour or grayscale output." },
    { name: "Convert", text: "Click Convert — CrispPDF renders each page in your browser using PDF.js." },
    { name: "Download images", text: "Grab each JPG individually or download the whole set as a ZIP." },
  ],
  "pdf-to-png": [
    { name: "Upload the PDF", text: "Drop the PDF you need as lossless images — perfect for screenshots and design assets." },
    { name: "Set resolution", text: "Pick the DPI. PNG output preserves transparency and sharp edges without compression artefacts." },
    { name: "Convert to PNG", text: "Click Convert. Each page renders as a standalone PNG file inside your browser." },
    { name: "Download the PNGs", text: "Save individual pages or download the full ZIP archive." },
  ],
  "word-to-pdf": [
    { name: "Upload the Word file", text: "Drop your .docx or .doc into the converter." },
    { name: "Convert to PDF", text: "Click Convert. Fonts, headings, tables, headers and footers all transfer intact." },
    { name: "Preview the layout", text: "Check the first page preview to confirm the formatting looks right." },
    { name: "Download the PDF", text: "Your final PDF downloads — ready to email, sign, or archive without further editing." },
  ],
  "excel-to-pdf": [
    { name: "Upload the spreadsheet", text: "Drop your .xlsx or .xls file into the converter." },
    { name: "Pick print options", text: "Choose portrait or landscape, fit-to-page scaling, and which sheets to include." },
    { name: "Convert to PDF", text: "Click Convert. CrispPDF renders each sheet with clean grid lines and preserved formulas as values." },
    { name: "Download the PDF", text: "Get a print-ready PDF you can email or archive — no Excel install needed to view it." },
  ],
  "jpg-to-pdf": [
    { name: "Add your images", text: "Drop JPG, PNG, WebP, or HEIC images into the upload zone — one at a time or as a batch." },
    { name: "Reorder and pick page size", text: "Drag thumbnails to reorder, then choose A4, Letter, or fit-to-image for the page size." },
    { name: "Convert to PDF", text: "Click Convert. Every image becomes a page in a single multipage PDF." },
    { name: "Download the PDF", text: "One tidy PDF downloads — ideal for exam uploads, receipts, or photo albums." },
  ],
  "html-to-pdf": [
    { name: "Paste the URL or HTML", text: "Enter any public web address, or paste raw HTML you want to save as a PDF." },
    { name: "Choose page size and margins", text: "Pick A4 or Letter, set margins, and toggle background graphics on or off." },
    { name: "Render to PDF", text: "Click Convert. The page is rendered server-side in a headless browser to preserve fonts and CSS." },
    { name: "Download the PDF", text: "Your archived webpage downloads as a clean, shareable PDF." },
  ],
  "rotate-pdf": [
    { name: "Upload the PDF", text: "Drop the file with sideways or upside-down pages into the tool." },
    { name: "Rotate pages", text: "Click the left- or right-rotate arrow on individual thumbnails, or rotate every page at once." },
    { name: "Apply the rotation", text: "Click Save — the rotation is permanent, not just a temporary view change." },
    { name: "Download the fixed PDF", text: "The corrected PDF downloads with every page oriented the right way up." },
  ],
  "reorder-pdf-pages": [
    { name: "Upload the PDF", text: "Drop your PDF in and CrispPDF renders a thumbnail grid of every page." },
    { name: "Drag thumbnails", text: "Rearrange pages by dragging them into the order you want the final document to follow." },
    { name: "Save the new order", text: "Click Save. CrispPDF rebuilds the PDF with the new page sequence — locally, in your browser." },
    { name: "Download the reordered PDF", text: "The reorganised PDF downloads instantly, with all bookmarks and links intact." },
  ],
  "delete-pdf-pages": [
    { name: "Upload the PDF", text: "Drop the PDF that contains pages you want to remove — blanks, ads, duplicates, or anything else." },
    { name: "Select pages to delete", text: "Click the trash icon on every thumbnail you no longer need." },
    { name: "Apply deletion", text: "Click Save — CrispPDF removes those pages and rewrites the file locally." },
    { name: "Download the trimmed PDF", text: "The slimmer PDF downloads with only the pages you kept." },
  ],
  "extract-pdf-pages": [
    { name: "Upload the source PDF", text: "Drop the PDF you want to pull specific pages from." },
    { name: "Select pages", text: "Tap the pages you want to keep, or enter a range like 3-7, 12, 20." },
    { name: "Extract", text: "Click Extract. CrispPDF builds a new PDF containing only those pages." },
    { name: "Download the new PDF", text: "Save the extracted file — the original stays untouched on your device." },
  ],
  "crop-pdf": [
    { name: "Upload the PDF", text: "Drop the PDF with unwanted margins or scanner white space into the tool." },
    { name: "Draw a crop rectangle", text: "Drag a box over the region you want to keep on the preview page." },
    { name: "Apply to one page or all", text: "Choose to crop the current page, a range, or every page in the document." },
    { name: "Download the cropped PDF", text: "The tidy, borderless PDF downloads with margins removed cleanly." },
  ],
  "repair-pdf": [
    { name: "Upload the damaged PDF", text: "Drop the file that refuses to open, throws errors, or shows blank pages." },
    { name: "Scan for corruption", text: "CrispPDF reads the raw structure and rebuilds the xref table and object streams where possible." },
    { name: "Repair", text: "Click Repair. Recoverable pages, text, and images are pulled into a fresh, valid PDF." },
    { name: "Download the fixed PDF", text: "Save the repaired file and reopen it in any reader — most partial-corruption cases restore fully." },
  ],
  "flatten-pdf": [
    { name: "Upload the PDF", text: "Drop a PDF that contains form fields, annotations, or comments you want to lock in." },
    { name: "Preview the layers", text: "CrispPDF shows every editable layer so you know exactly what will be baked into the page." },
    { name: "Flatten", text: "Click Flatten. All annotations, filled fields, and stamps become part of the page — no longer editable." },
    { name: "Download the flat PDF", text: "The frozen PDF downloads, safe to share without recipients being able to alter form values." },
  ],
  "pdf-to-pdfa": [
    { name: "Upload the PDF", text: "Drop the PDF you need in the archival PDF/A format for long-term storage or legal filing." },
    { name: "Pick a PDF/A level", text: "Choose PDF/A-1b, 2b, or 3b depending on your archive or compliance requirements." },
    { name: "Convert", text: "Click Convert. Fonts are embedded, colour profiles standardised, and unsupported features stripped." },
    { name: "Download the PDF/A", text: "The compliant, archive-ready file downloads with an embedded PDF/A marker." },
  ],
  "grayscale-pdf": [
    { name: "Upload the PDF", text: "Drop a colour PDF you want to convert to pure black-and-white for cheaper printing." },
    { name: "Preview grayscale pages", text: "CrispPDF renders a live grayscale preview so you can confirm the result before saving." },
    { name: "Convert to grayscale", text: "Click Convert. Every colour value is remapped to grayscale without touching text sharpness." },
    { name: "Download the B&W PDF", text: "The grayscale PDF downloads — smaller in size and print-cost-friendly." },
  ],
  "protect-pdf": [
    { name: "Upload the PDF", text: "Drop the PDF you want to secure with a password." },
    { name: "Set a strong password", text: "Enter a password (and optionally an owner password) and pick AES-256 encryption." },
    { name: "Choose restrictions", text: "Optionally restrict printing, copying, or editing without the owner password." },
    { name: "Download the protected PDF", text: "Save the encrypted PDF — password and file never leave your browser." },
  ],
  "unlock-pdf": [
    { name: "Upload the locked PDF", text: "Drop the password-protected PDF you own into the tool." },
    { name: "Enter the password", text: "Type the current password. Owner-only restrictions (print/copy) can often be removed without one." },
    { name: "Unlock", text: "Click Unlock. CrispPDF decrypts the file locally — nothing is transmitted to a server." },
    { name: "Download the unlocked PDF", text: "Save the plain, password-free PDF, ready to view or edit on any device." },
  ],
  "redact-pdf": [
    { name: "Upload the PDF", text: "Drop the document that contains sensitive names, numbers, or signatures." },
    { name: "Draw redaction boxes", text: "Drag black rectangles over anything you need to remove — text underneath is deleted, not just covered." },
    { name: "Apply redactions", text: "Click Redact. CrispPDF strips the underlying text stream so redacted content can't be recovered." },
    { name: "Download the redacted PDF", text: "The safely-redacted PDF downloads — suitable for court filings, FOIA, or public sharing." },
  ],
  "esign-pdf": [
    { name: "Upload the PDF", text: "Drop the contract, form, or letter you need to sign." },
    { name: "Create your signature", text: "Draw with a finger or stylus, type in a script font, or upload a PNG of your handwritten signature." },
    { name: "Place and resize", text: "Drag the signature onto the correct page, resize it, and add a date or initials if needed." },
    { name: "Download the signed PDF", text: "Save the finalised PDF — legally valid for most everyday agreements, no DocuSign account required." },
  ],
  "watermark-pdf": [
    { name: "Upload the PDF", text: "Drop the document you want to mark with a logo or stamp image." },
    { name: "Upload the watermark", text: "Add a PNG or JPG watermark and set its opacity, angle, and position on the page." },
    { name: "Apply to selected pages", text: "Watermark every page or only a range, and preview the result before saving." },
    { name: "Download the watermarked PDF", text: "The stamped PDF downloads — perfect for draft copies, confidentiality marks, or brand identity." },
  ],
  "ocr-pdf": [
    { name: "Upload the scanned PDF", text: "Drop an image-only PDF — the kind you can't select text from." },
    { name: "Pick languages", text: "Choose one or more languages (Tesseract supports 100+, including Hindi, English, Spanish, and Chinese)." },
    { name: "Run OCR", text: "Click Recognise. Text is detected page by page inside your browser — no upload." },
    { name: "Download the searchable PDF", text: "Save the new PDF with a transparent text layer — fully searchable, copyable, and translation-ready." },
  ],
  "add-page-numbers-pdf": [
    { name: "Upload the PDF", text: "Drop the document you want to number." },
    { name: "Pick number style", text: "Choose the position (header/footer, left/centre/right), font, size, and starting number." },
    { name: "Add numbers", text: "Click Apply. Numbers are drawn into the PDF at the exact position you selected." },
    { name: "Download the numbered PDF", text: "Save the paginated PDF — ideal for reports, dissertations, and legal filings." },
  ],
  "add-watermark-text-pdf": [
    { name: "Upload the PDF", text: "Drop the file that needs a text stamp — 'Draft', 'Confidential', a URL, or a name." },
    { name: "Type the watermark", text: "Enter the text and pick font, colour, size, angle, and opacity." },
    { name: "Pick pages", text: "Apply the watermark to every page or only a specific range." },
    { name: "Download the marked PDF", text: "Save the stamped PDF — a light, readable watermark sits on every chosen page." },
  ],
  "extract-images-pdf": [
    { name: "Upload the PDF", text: "Drop a PDF that contains photos, diagrams, or charts you want as separate image files." },
    { name: "Scan for images", text: "CrispPDF walks the PDF and lists every embedded image with a preview thumbnail." },
    { name: "Pick which to extract", text: "Select the images you need or grab them all at once." },
    { name: "Download images", text: "Save individual images or download the whole set as a ZIP — original resolution preserved." },
  ],
  "invert-pdf": [
    { name: "Upload the PDF", text: "Drop a PDF you want in dark mode — great for reading at night or saving ink on dark backgrounds." },
    { name: "Preview inverted pages", text: "See the colour-inverted result before you commit, so black text becomes white on black." },
    { name: "Invert colours", text: "Click Invert. Every colour value is negated across every page." },
    { name: "Download the inverted PDF", text: "Save the dark-mode PDF — easier on the eyes late at night." },
  ],
  "resize-pdf": [
    { name: "Upload the PDF", text: "Drop the PDF whose page dimensions you need to change." },
    { name: "Pick a new page size", text: "Choose A4, Letter, A3, or a custom width and height in mm or inches." },
    { name: "Resize", text: "Click Resize. Pages are scaled or repositioned to fit the new dimensions without cropping content." },
    { name: "Download the resized PDF", text: "Save the correctly-sized PDF, ready for print or archival." },
  ],
  "n-up-pdf": [
    { name: "Upload the PDF", text: "Drop the document you want to print with multiple pages per sheet." },
    { name: "Pick a layout", text: "Choose 2-up, 4-up, 6-up, or 9-up and set the page order (rows or columns first)." },
    { name: "Generate", text: "Click Apply. Pages are arranged onto larger sheets with even margins." },
    { name: "Download the N-up PDF", text: "Save the paper-saving PDF — great for handouts, booklets, and study notes." },
  ],
  "blank-page-pdf": [
    { name: "Pick page size", text: "Choose A4, Letter, or a custom size — plus portrait or landscape." },
    { name: "Set page count", text: "Enter how many blank pages you need (1, 10, 100 — up to you)." },
    { name: "Generate", text: "Click Create. CrispPDF builds an empty PDF instantly inside your browser." },
    { name: "Download the blank PDF", text: "Save the empty PDF — useful for spacers, cover sheets, or template starters." },
  ],
  "duplicate-pages-pdf": [
    { name: "Upload the PDF", text: "Drop the source PDF that contains the page you want to clone." },
    { name: "Select pages to duplicate", text: "Pick the page(s) to copy and how many times each should repeat." },
    { name: "Duplicate", text: "Click Apply. The chosen pages are inserted at the position you specify." },
    { name: "Download the expanded PDF", text: "Save the new PDF containing your duplicated pages, ready for form printing or booklet layout." },
  ],
  "extract-text-pdf": [
    { name: "Upload the PDF", text: "Drop a text-based PDF (not a scan) into the tool." },
    { name: "Extract text", text: "Click Extract. CrispPDF reads the text streams page by page inside your browser." },
    { name: "Preview and copy", text: "Review the extracted text in the preview pane and copy anything you need." },
    { name: "Download as .txt", text: "Save the full text as a plain .txt file for indexing, translation, or reuse." },
  ],
  "edit-metadata-pdf": [
    { name: "Upload the PDF", text: "Drop the file whose title, author, or keywords you want to change." },
    { name: "Edit metadata fields", text: "Update Title, Author, Subject, Keywords, and the created/modified timestamps." },
    { name: "Save changes", text: "Click Save. The metadata is rewritten while every page stays exactly as it was." },
    { name: "Download the updated PDF", text: "Save the file — new metadata is embedded, useful for archiving, SEO, or scrubbing identifying info." },
  ],
  "compare-pdf": [
    { name: "Upload both PDFs", text: "Drop the original PDF on the left and the revised PDF on the right." },
    { name: "Run the diff", text: "Click Compare. CrispPDF highlights added, removed, and moved text page by page." },
    { name: "Review changes", text: "Step through the changes with side-by-side previews and colour-coded markers." },
    { name: "Download the diff report", text: "Save a PDF report of the differences — perfect for contract review and version audits." },
  ],
  "base64-pdf": [
    { name: "Pick a direction", text: "Choose PDF → Base64 to encode a PDF, or Base64 → PDF to decode a text string back into a PDF." },
    { name: "Upload or paste", text: "Drop a PDF file, or paste a Base64 string into the input box." },
    { name: "Convert", text: "Click Convert. CrispPDF encodes or decodes locally, safe for API payloads and email pipelines." },
    { name: "Download or copy", text: "Copy the Base64 string, or download the decoded PDF, whichever direction you chose." },
  ],
  "reverse-pdf": [
    { name: "Upload the PDF", text: "Drop the PDF whose page order needs to be flipped end-to-end." },
    { name: "Preview reversed order", text: "CrispPDF shows a thumbnail of the reversed sequence so you can confirm before saving." },
    { name: "Reverse", text: "Click Apply. The last page becomes the first, second-to-last becomes the second, and so on." },
    { name: "Download the reversed PDF", text: "Save the correctly-ordered PDF — great for fixing back-to-front scans." },
  ],
};
