/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WordToPdfRouteImport } from './routes/word-to-pdf'
import { Route as WatermarkPdfRouteImport } from './routes/watermark-pdf'
import { Route as UnlockPdfRouteImport } from './routes/unlock-pdf'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SplitPdfRouteImport } from './routes/split-pdf'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SecurePdfRouteImport } from './routes/secure-pdf'
import { Route as RotatePdfRouteImport } from './routes/rotate-pdf'
import { Route as ReversePdfRouteImport } from './routes/reverse-pdf'
import { Route as ResizePdfRouteImport } from './routes/resize-pdf'
import { Route as RepairPdfRouteImport } from './routes/repair-pdf'
import { Route as ReorderPdfPagesRouteImport } from './routes/reorder-pdf-pages'
import { Route as RedactPdfRouteImport } from './routes/redact-pdf'
import { Route as ProtectPdfRouteImport } from './routes/protect-pdf'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PdfToWordRouteImport } from './routes/pdf-to-word'
import { Route as PdfToPptRouteImport } from './routes/pdf-to-ppt'
import { Route as PdfToPngRouteImport } from './routes/pdf-to-png'
import { Route as PdfToPdfaRouteImport } from './routes/pdf-to-pdfa'
import { Route as PdfToJpgRouteImport } from './routes/pdf-to-jpg'
import { Route as PdfToExcelRouteImport } from './routes/pdf-to-excel'
import { Route as OrganizePdfRouteImport } from './routes/organize-pdf'
import { Route as OcrPdfRouteImport } from './routes/ocr-pdf'
import { Route as NUpPdfRouteImport } from './routes/n-up-pdf'
import { Route as MergePdfRouteImport } from './routes/merge-pdf'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as LlmsFullDottxtRouteImport } from './routes/llms-full[.]txt'
import { Route as JpgToPdfRouteImport } from './routes/jpg-to-pdf'
import { Route as InvertPdfRouteImport } from './routes/invert-pdf'
import { Route as HtmlToPdfRouteImport } from './routes/html-to-pdf'
import { Route as GrayscalePdfRouteImport } from './routes/grayscale-pdf'
import { Route as FlattenPdfRouteImport } from './routes/flatten-pdf'
import { Route as ExtractTextPdfRouteImport } from './routes/extract-text-pdf'
import { Route as ExtractPdfPagesRouteImport } from './routes/extract-pdf-pages'
import { Route as ExtractImagesPdfRouteImport } from './routes/extract-images-pdf'
import { Route as ExcelToPdfRouteImport } from './routes/excel-to-pdf'
import { Route as EsignPdfRouteImport } from './routes/esign-pdf'
import { Route as EditPdfRouteImport } from './routes/edit-pdf'
import { Route as EditMetadataPdfRouteImport } from './routes/edit-metadata-pdf'
import { Route as DuplicatePagesPdfRouteImport } from './routes/duplicate-pages-pdf'
import { Route as DeletePdfPagesRouteImport } from './routes/delete-pdf-pages'
import { Route as CropPdfRouteImport } from './routes/crop-pdf'
import { Route as ConvertPdfRouteImport } from './routes/convert-pdf'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompressPdfRouteImport } from './routes/compress-pdf'
import { Route as ComparePdfRouteImport } from './routes/compare-pdf'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BlankPagePdfRouteImport } from './routes/blank-page-pdf'
import { Route as Base64PdfRouteImport } from './routes/base64-pdf'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AiDottxtRouteImport } from './routes/ai[.]txt'
import { Route as AddWatermarkTextPdfRouteImport } from './routes/add-watermark-text-pdf'
import { Route as AddPageNumbersPdfRouteImport } from './routes/add-page-numbers-pdf'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VsSlugRouteImport } from './routes/vs.$slug'
import { Route as UseCasesSlugRouteImport } from './routes/use-cases.$slug'
import { Route as ToolsSlugRouteImport } from './routes/tools.$slug'
import { Route as ConvertSlugRouteImport } from './routes/convert.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthenticatedCpCrisp7x92kRouteImport } from './routes/_authenticated/cp-crisp-7x92k'

const WordToPdfRoute = WordToPdfRouteImport.update({
  id: '/word-to-pdf',
  path: '/word-to-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const WatermarkPdfRoute = WatermarkPdfRouteImport.update({
  id: '/watermark-pdf',
  path: '/watermark-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const UnlockPdfRoute = UnlockPdfRouteImport.update({
  id: '/unlock-pdf',
  path: '/unlock-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SplitPdfRoute = SplitPdfRouteImport.update({
  id: '/split-pdf',
  path: '/split-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurePdfRoute = SecurePdfRouteImport.update({
  id: '/secure-pdf',
  path: '/secure-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const RotatePdfRoute = RotatePdfRouteImport.update({
  id: '/rotate-pdf',
  path: '/rotate-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ReversePdfRoute = ReversePdfRouteImport.update({
  id: '/reverse-pdf',
  path: '/reverse-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ResizePdfRoute = ResizePdfRouteImport.update({
  id: '/resize-pdf',
  path: '/resize-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const RepairPdfRoute = RepairPdfRouteImport.update({
  id: '/repair-pdf',
  path: '/repair-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ReorderPdfPagesRoute = ReorderPdfPagesRouteImport.update({
  id: '/reorder-pdf-pages',
  path: '/reorder-pdf-pages',
  getParentRoute: () => rootRouteImport,
} as any)
const RedactPdfRoute = RedactPdfRouteImport.update({
  id: '/redact-pdf',
  path: '/redact-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectPdfRoute = ProtectPdfRouteImport.update({
  id: '/protect-pdf',
  path: '/protect-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfToWordRoute = PdfToWordRouteImport.update({
  id: '/pdf-to-word',
  path: '/pdf-to-word',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfToPptRoute = PdfToPptRouteImport.update({
  id: '/pdf-to-ppt',
  path: '/pdf-to-ppt',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfToPngRoute = PdfToPngRouteImport.update({
  id: '/pdf-to-png',
  path: '/pdf-to-png',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfToPdfaRoute = PdfToPdfaRouteImport.update({
  id: '/pdf-to-pdfa',
  path: '/pdf-to-pdfa',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfToJpgRoute = PdfToJpgRouteImport.update({
  id: '/pdf-to-jpg',
  path: '/pdf-to-jpg',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfToExcelRoute = PdfToExcelRouteImport.update({
  id: '/pdf-to-excel',
  path: '/pdf-to-excel',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizePdfRoute = OrganizePdfRouteImport.update({
  id: '/organize-pdf',
  path: '/organize-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const OcrPdfRoute = OcrPdfRouteImport.update({
  id: '/ocr-pdf',
  path: '/ocr-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const NUpPdfRoute = NUpPdfRouteImport.update({
  id: '/n-up-pdf',
  path: '/n-up-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const MergePdfRoute = MergePdfRouteImport.update({
  id: '/merge-pdf',
  path: '/merge-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsFullDottxtRoute = LlmsFullDottxtRouteImport.update({
  id: '/llms-full.txt',
  path: '/llms-full.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const JpgToPdfRoute = JpgToPdfRouteImport.update({
  id: '/jpg-to-pdf',
  path: '/jpg-to-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const InvertPdfRoute = InvertPdfRouteImport.update({
  id: '/invert-pdf',
  path: '/invert-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const HtmlToPdfRoute = HtmlToPdfRouteImport.update({
  id: '/html-to-pdf',
  path: '/html-to-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const GrayscalePdfRoute = GrayscalePdfRouteImport.update({
  id: '/grayscale-pdf',
  path: '/grayscale-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const FlattenPdfRoute = FlattenPdfRouteImport.update({
  id: '/flatten-pdf',
  path: '/flatten-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtractTextPdfRoute = ExtractTextPdfRouteImport.update({
  id: '/extract-text-pdf',
  path: '/extract-text-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtractPdfPagesRoute = ExtractPdfPagesRouteImport.update({
  id: '/extract-pdf-pages',
  path: '/extract-pdf-pages',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtractImagesPdfRoute = ExtractImagesPdfRouteImport.update({
  id: '/extract-images-pdf',
  path: '/extract-images-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ExcelToPdfRoute = ExcelToPdfRouteImport.update({
  id: '/excel-to-pdf',
  path: '/excel-to-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const EsignPdfRoute = EsignPdfRouteImport.update({
  id: '/esign-pdf',
  path: '/esign-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const EditPdfRoute = EditPdfRouteImport.update({
  id: '/edit-pdf',
  path: '/edit-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const EditMetadataPdfRoute = EditMetadataPdfRouteImport.update({
  id: '/edit-metadata-pdf',
  path: '/edit-metadata-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const DuplicatePagesPdfRoute = DuplicatePagesPdfRouteImport.update({
  id: '/duplicate-pages-pdf',
  path: '/duplicate-pages-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const DeletePdfPagesRoute = DeletePdfPagesRouteImport.update({
  id: '/delete-pdf-pages',
  path: '/delete-pdf-pages',
  getParentRoute: () => rootRouteImport,
} as any)
const CropPdfRoute = CropPdfRouteImport.update({
  id: '/crop-pdf',
  path: '/crop-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ConvertPdfRoute = ConvertPdfRouteImport.update({
  id: '/convert-pdf',
  path: '/convert-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompressPdfRoute = CompressPdfRouteImport.update({
  id: '/compress-pdf',
  path: '/compress-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparePdfRoute = ComparePdfRouteImport.update({
  id: '/compare-pdf',
  path: '/compare-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BlankPagePdfRoute = BlankPagePdfRouteImport.update({
  id: '/blank-page-pdf',
  path: '/blank-page-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const Base64PdfRoute = Base64PdfRouteImport.update({
  id: '/base64-pdf',
  path: '/base64-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AiDottxtRoute = AiDottxtRouteImport.update({
  id: '/ai.txt',
  path: '/ai.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const AddWatermarkTextPdfRoute = AddWatermarkTextPdfRouteImport.update({
  id: '/add-watermark-text-pdf',
  path: '/add-watermark-text-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const AddPageNumbersPdfRoute = AddPageNumbersPdfRouteImport.update({
  id: '/add-page-numbers-pdf',
  path: '/add-page-numbers-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VsSlugRoute = VsSlugRouteImport.update({
  id: '/vs/$slug',
  path: '/vs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const UseCasesSlugRoute = UseCasesSlugRouteImport.update({
  id: '/use-cases/$slug',
  path: '/use-cases/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsSlugRoute = ToolsSlugRouteImport.update({
  id: '/tools/$slug',
  path: '/tools/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ConvertSlugRoute = ConvertSlugRouteImport.update({
  id: '/convert/$slug',
  path: '/convert/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AuthenticatedCpCrisp7x92kRoute =
  AuthenticatedCpCrisp7x92kRouteImport.update({
    id: '/cp-crisp-7x92k',
    path: '/cp-crisp-7x92k',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/add-page-numbers-pdf': typeof AddPageNumbersPdfRoute
  '/add-watermark-text-pdf': typeof AddWatermarkTextPdfRoute
  '/ai.txt': typeof AiDottxtRoute
  '/auth': typeof AuthRoute
  '/base64-pdf': typeof Base64PdfRoute
  '/blank-page-pdf': typeof BlankPagePdfRoute
  '/blog': typeof BlogRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/compare-pdf': typeof ComparePdfRoute
  '/compress-pdf': typeof CompressPdfRoute
  '/contact': typeof ContactRoute
  '/convert-pdf': typeof ConvertPdfRoute
  '/crop-pdf': typeof CropPdfRoute
  '/delete-pdf-pages': typeof DeletePdfPagesRoute
  '/duplicate-pages-pdf': typeof DuplicatePagesPdfRoute
  '/edit-metadata-pdf': typeof EditMetadataPdfRoute
  '/edit-pdf': typeof EditPdfRoute
  '/esign-pdf': typeof EsignPdfRoute
  '/excel-to-pdf': typeof ExcelToPdfRoute
  '/extract-images-pdf': typeof ExtractImagesPdfRoute
  '/extract-pdf-pages': typeof ExtractPdfPagesRoute
  '/extract-text-pdf': typeof ExtractTextPdfRoute
  '/flatten-pdf': typeof FlattenPdfRoute
  '/grayscale-pdf': typeof GrayscalePdfRoute
  '/html-to-pdf': typeof HtmlToPdfRoute
  '/invert-pdf': typeof InvertPdfRoute
  '/jpg-to-pdf': typeof JpgToPdfRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/merge-pdf': typeof MergePdfRoute
  '/n-up-pdf': typeof NUpPdfRoute
  '/ocr-pdf': typeof OcrPdfRoute
  '/organize-pdf': typeof OrganizePdfRoute
  '/pdf-to-excel': typeof PdfToExcelRoute
  '/pdf-to-jpg': typeof PdfToJpgRoute
  '/pdf-to-pdfa': typeof PdfToPdfaRoute
  '/pdf-to-png': typeof PdfToPngRoute
  '/pdf-to-ppt': typeof PdfToPptRoute
  '/pdf-to-word': typeof PdfToWordRoute
  '/privacy': typeof PrivacyRoute
  '/protect-pdf': typeof ProtectPdfRoute
  '/redact-pdf': typeof RedactPdfRoute
  '/reorder-pdf-pages': typeof ReorderPdfPagesRoute
  '/repair-pdf': typeof RepairPdfRoute
  '/resize-pdf': typeof ResizePdfRoute
  '/reverse-pdf': typeof ReversePdfRoute
  '/rotate-pdf': typeof RotatePdfRoute
  '/secure-pdf': typeof SecurePdfRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/split-pdf': typeof SplitPdfRoute
  '/terms': typeof TermsRoute
  '/unlock-pdf': typeof UnlockPdfRoute
  '/watermark-pdf': typeof WatermarkPdfRoute
  '/word-to-pdf': typeof WordToPdfRoute
  '/cp-crisp-7x92k': typeof AuthenticatedCpCrisp7x92kRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/convert/$slug': typeof ConvertSlugRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/use-cases/$slug': typeof UseCasesSlugRoute
  '/vs/$slug': typeof VsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/add-page-numbers-pdf': typeof AddPageNumbersPdfRoute
  '/add-watermark-text-pdf': typeof AddWatermarkTextPdfRoute
  '/ai.txt': typeof AiDottxtRoute
  '/auth': typeof AuthRoute
  '/base64-pdf': typeof Base64PdfRoute
  '/blank-page-pdf': typeof BlankPagePdfRoute
  '/blog': typeof BlogRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/compare-pdf': typeof ComparePdfRoute
  '/compress-pdf': typeof CompressPdfRoute
  '/contact': typeof ContactRoute
  '/convert-pdf': typeof ConvertPdfRoute
  '/crop-pdf': typeof CropPdfRoute
  '/delete-pdf-pages': typeof DeletePdfPagesRoute
  '/duplicate-pages-pdf': typeof DuplicatePagesPdfRoute
  '/edit-metadata-pdf': typeof EditMetadataPdfRoute
  '/edit-pdf': typeof EditPdfRoute
  '/esign-pdf': typeof EsignPdfRoute
  '/excel-to-pdf': typeof ExcelToPdfRoute
  '/extract-images-pdf': typeof ExtractImagesPdfRoute
  '/extract-pdf-pages': typeof ExtractPdfPagesRoute
  '/extract-text-pdf': typeof ExtractTextPdfRoute
  '/flatten-pdf': typeof FlattenPdfRoute
  '/grayscale-pdf': typeof GrayscalePdfRoute
  '/html-to-pdf': typeof HtmlToPdfRoute
  '/invert-pdf': typeof InvertPdfRoute
  '/jpg-to-pdf': typeof JpgToPdfRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/merge-pdf': typeof MergePdfRoute
  '/n-up-pdf': typeof NUpPdfRoute
  '/ocr-pdf': typeof OcrPdfRoute
  '/organize-pdf': typeof OrganizePdfRoute
  '/pdf-to-excel': typeof PdfToExcelRoute
  '/pdf-to-jpg': typeof PdfToJpgRoute
  '/pdf-to-pdfa': typeof PdfToPdfaRoute
  '/pdf-to-png': typeof PdfToPngRoute
  '/pdf-to-ppt': typeof PdfToPptRoute
  '/pdf-to-word': typeof PdfToWordRoute
  '/privacy': typeof PrivacyRoute
  '/protect-pdf': typeof ProtectPdfRoute
  '/redact-pdf': typeof RedactPdfRoute
  '/reorder-pdf-pages': typeof ReorderPdfPagesRoute
  '/repair-pdf': typeof RepairPdfRoute
  '/resize-pdf': typeof ResizePdfRoute
  '/reverse-pdf': typeof ReversePdfRoute
  '/rotate-pdf': typeof RotatePdfRoute
  '/secure-pdf': typeof SecurePdfRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/split-pdf': typeof SplitPdfRoute
  '/terms': typeof TermsRoute
  '/unlock-pdf': typeof UnlockPdfRoute
  '/watermark-pdf': typeof WatermarkPdfRoute
  '/word-to-pdf': typeof WordToPdfRoute
  '/cp-crisp-7x92k': typeof AuthenticatedCpCrisp7x92kRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/convert/$slug': typeof ConvertSlugRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/use-cases/$slug': typeof UseCasesSlugRoute
  '/vs/$slug': typeof VsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/add-page-numbers-pdf': typeof AddPageNumbersPdfRoute
  '/add-watermark-text-pdf': typeof AddWatermarkTextPdfRoute
  '/ai.txt': typeof AiDottxtRoute
  '/auth': typeof AuthRoute
  '/base64-pdf': typeof Base64PdfRoute
  '/blank-page-pdf': typeof BlankPagePdfRoute
  '/blog': typeof BlogRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/compare-pdf': typeof ComparePdfRoute
  '/compress-pdf': typeof CompressPdfRoute
  '/contact': typeof ContactRoute
  '/convert-pdf': typeof ConvertPdfRoute
  '/crop-pdf': typeof CropPdfRoute
  '/delete-pdf-pages': typeof DeletePdfPagesRoute
  '/duplicate-pages-pdf': typeof DuplicatePagesPdfRoute
  '/edit-metadata-pdf': typeof EditMetadataPdfRoute
  '/edit-pdf': typeof EditPdfRoute
  '/esign-pdf': typeof EsignPdfRoute
  '/excel-to-pdf': typeof ExcelToPdfRoute
  '/extract-images-pdf': typeof ExtractImagesPdfRoute
  '/extract-pdf-pages': typeof ExtractPdfPagesRoute
  '/extract-text-pdf': typeof ExtractTextPdfRoute
  '/flatten-pdf': typeof FlattenPdfRoute
  '/grayscale-pdf': typeof GrayscalePdfRoute
  '/html-to-pdf': typeof HtmlToPdfRoute
  '/invert-pdf': typeof InvertPdfRoute
  '/jpg-to-pdf': typeof JpgToPdfRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/merge-pdf': typeof MergePdfRoute
  '/n-up-pdf': typeof NUpPdfRoute
  '/ocr-pdf': typeof OcrPdfRoute
  '/organize-pdf': typeof OrganizePdfRoute
  '/pdf-to-excel': typeof PdfToExcelRoute
  '/pdf-to-jpg': typeof PdfToJpgRoute
  '/pdf-to-pdfa': typeof PdfToPdfaRoute
  '/pdf-to-png': typeof PdfToPngRoute
  '/pdf-to-ppt': typeof PdfToPptRoute
  '/pdf-to-word': typeof PdfToWordRoute
  '/privacy': typeof PrivacyRoute
  '/protect-pdf': typeof ProtectPdfRoute
  '/redact-pdf': typeof RedactPdfRoute
  '/reorder-pdf-pages': typeof ReorderPdfPagesRoute
  '/repair-pdf': typeof RepairPdfRoute
  '/resize-pdf': typeof ResizePdfRoute
  '/reverse-pdf': typeof ReversePdfRoute
  '/rotate-pdf': typeof RotatePdfRoute
  '/secure-pdf': typeof SecurePdfRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/split-pdf': typeof SplitPdfRoute
  '/terms': typeof TermsRoute
  '/unlock-pdf': typeof UnlockPdfRoute
  '/watermark-pdf': typeof WatermarkPdfRoute
  '/word-to-pdf': typeof WordToPdfRoute
  '/_authenticated/cp-crisp-7x92k': typeof AuthenticatedCpCrisp7x92kRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/convert/$slug': typeof ConvertSlugRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/use-cases/$slug': typeof UseCasesSlugRoute
  '/vs/$slug': typeof VsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/add-page-numbers-pdf'
    | '/add-watermark-text-pdf'
    | '/ai.txt'
    | '/auth'
    | '/base64-pdf'
    | '/blank-page-pdf'
    | '/blog'
    | '/changelog'
    | '/compare-pdf'
    | '/compress-pdf'
    | '/contact'
    | '/convert-pdf'
    | '/crop-pdf'
    | '/delete-pdf-pages'
    | '/duplicate-pages-pdf'
    | '/edit-metadata-pdf'
    | '/edit-pdf'
    | '/esign-pdf'
    | '/excel-to-pdf'
    | '/extract-images-pdf'
    | '/extract-pdf-pages'
    | '/extract-text-pdf'
    | '/flatten-pdf'
    | '/grayscale-pdf'
    | '/html-to-pdf'
    | '/invert-pdf'
    | '/jpg-to-pdf'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/merge-pdf'
    | '/n-up-pdf'
    | '/ocr-pdf'
    | '/organize-pdf'
    | '/pdf-to-excel'
    | '/pdf-to-jpg'
    | '/pdf-to-pdfa'
    | '/pdf-to-png'
    | '/pdf-to-ppt'
    | '/pdf-to-word'
    | '/privacy'
    | '/protect-pdf'
    | '/redact-pdf'
    | '/reorder-pdf-pages'
    | '/repair-pdf'
    | '/resize-pdf'
    | '/reverse-pdf'
    | '/rotate-pdf'
    | '/secure-pdf'
    | '/sitemap.xml'
    | '/split-pdf'
    | '/terms'
    | '/unlock-pdf'
    | '/watermark-pdf'
    | '/word-to-pdf'
    | '/cp-crisp-7x92k'
    | '/blog/$slug'
    | '/convert/$slug'
    | '/tools/$slug'
    | '/use-cases/$slug'
    | '/vs/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/add-page-numbers-pdf'
    | '/add-watermark-text-pdf'
    | '/ai.txt'
    | '/auth'
    | '/base64-pdf'
    | '/blank-page-pdf'
    | '/blog'
    | '/changelog'
    | '/compare-pdf'
    | '/compress-pdf'
    | '/contact'
    | '/convert-pdf'
    | '/crop-pdf'
    | '/delete-pdf-pages'
    | '/duplicate-pages-pdf'
    | '/edit-metadata-pdf'
    | '/edit-pdf'
    | '/esign-pdf'
    | '/excel-to-pdf'
    | '/extract-images-pdf'
    | '/extract-pdf-pages'
    | '/extract-text-pdf'
    | '/flatten-pdf'
    | '/grayscale-pdf'
    | '/html-to-pdf'
    | '/invert-pdf'
    | '/jpg-to-pdf'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/merge-pdf'
    | '/n-up-pdf'
    | '/ocr-pdf'
    | '/organize-pdf'
    | '/pdf-to-excel'
    | '/pdf-to-jpg'
    | '/pdf-to-pdfa'
    | '/pdf-to-png'
    | '/pdf-to-ppt'
    | '/pdf-to-word'
    | '/privacy'
    | '/protect-pdf'
    | '/redact-pdf'
    | '/reorder-pdf-pages'
    | '/repair-pdf'
    | '/resize-pdf'
    | '/reverse-pdf'
    | '/rotate-pdf'
    | '/secure-pdf'
    | '/sitemap.xml'
    | '/split-pdf'
    | '/terms'
    | '/unlock-pdf'
    | '/watermark-pdf'
    | '/word-to-pdf'
    | '/cp-crisp-7x92k'
    | '/blog/$slug'
    | '/convert/$slug'
    | '/tools/$slug'
    | '/use-cases/$slug'
    | '/vs/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/add-page-numbers-pdf'
    | '/add-watermark-text-pdf'
    | '/ai.txt'
    | '/auth'
    | '/base64-pdf'
    | '/blank-page-pdf'
    | '/blog'
    | '/changelog'
    | '/compare-pdf'
    | '/compress-pdf'
    | '/contact'
    | '/convert-pdf'
    | '/crop-pdf'
    | '/delete-pdf-pages'
    | '/duplicate-pages-pdf'
    | '/edit-metadata-pdf'
    | '/edit-pdf'
    | '/esign-pdf'
    | '/excel-to-pdf'
    | '/extract-images-pdf'
    | '/extract-pdf-pages'
    | '/extract-text-pdf'
    | '/flatten-pdf'
    | '/grayscale-pdf'
    | '/html-to-pdf'
    | '/invert-pdf'
    | '/jpg-to-pdf'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/merge-pdf'
    | '/n-up-pdf'
    | '/ocr-pdf'
    | '/organize-pdf'
    | '/pdf-to-excel'
    | '/pdf-to-jpg'
    | '/pdf-to-pdfa'
    | '/pdf-to-png'
    | '/pdf-to-ppt'
    | '/pdf-to-word'
    | '/privacy'
    | '/protect-pdf'
    | '/redact-pdf'
    | '/reorder-pdf-pages'
    | '/repair-pdf'
    | '/resize-pdf'
    | '/reverse-pdf'
    | '/rotate-pdf'
    | '/secure-pdf'
    | '/sitemap.xml'
    | '/split-pdf'
    | '/terms'
    | '/unlock-pdf'
    | '/watermark-pdf'
    | '/word-to-pdf'
    | '/_authenticated/cp-crisp-7x92k'
    | '/blog/$slug'
    | '/convert/$slug'
    | '/tools/$slug'
    | '/use-cases/$slug'
    | '/vs/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AddPageNumbersPdfRoute: typeof AddPageNumbersPdfRoute
  AddWatermarkTextPdfRoute: typeof AddWatermarkTextPdfRoute
  AiDottxtRoute: typeof AiDottxtRoute
  AuthRoute: typeof AuthRoute
  Base64PdfRoute: typeof Base64PdfRoute
  BlankPagePdfRoute: typeof BlankPagePdfRoute
  BlogRoute: typeof BlogRouteWithChildren
  ChangelogRoute: typeof ChangelogRoute
  ComparePdfRoute: typeof ComparePdfRoute
  CompressPdfRoute: typeof CompressPdfRoute
  ContactRoute: typeof ContactRoute
  ConvertPdfRoute: typeof ConvertPdfRoute
  CropPdfRoute: typeof CropPdfRoute
  DeletePdfPagesRoute: typeof DeletePdfPagesRoute
  DuplicatePagesPdfRoute: typeof DuplicatePagesPdfRoute
  EditMetadataPdfRoute: typeof EditMetadataPdfRoute
  EditPdfRoute: typeof EditPdfRoute
  EsignPdfRoute: typeof EsignPdfRoute
  ExcelToPdfRoute: typeof ExcelToPdfRoute
  ExtractImagesPdfRoute: typeof ExtractImagesPdfRoute
  ExtractPdfPagesRoute: typeof ExtractPdfPagesRoute
  ExtractTextPdfRoute: typeof ExtractTextPdfRoute
  FlattenPdfRoute: typeof FlattenPdfRoute
  GrayscalePdfRoute: typeof GrayscalePdfRoute
  HtmlToPdfRoute: typeof HtmlToPdfRoute
  InvertPdfRoute: typeof InvertPdfRoute
  JpgToPdfRoute: typeof JpgToPdfRoute
  LlmsFullDottxtRoute: typeof LlmsFullDottxtRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  MergePdfRoute: typeof MergePdfRoute
  NUpPdfRoute: typeof NUpPdfRoute
  OcrPdfRoute: typeof OcrPdfRoute
  OrganizePdfRoute: typeof OrganizePdfRoute
  PdfToExcelRoute: typeof PdfToExcelRoute
  PdfToJpgRoute: typeof PdfToJpgRoute
  PdfToPdfaRoute: typeof PdfToPdfaRoute
  PdfToPngRoute: typeof PdfToPngRoute
  PdfToPptRoute: typeof PdfToPptRoute
  PdfToWordRoute: typeof PdfToWordRoute
  PrivacyRoute: typeof PrivacyRoute
  ProtectPdfRoute: typeof ProtectPdfRoute
  RedactPdfRoute: typeof RedactPdfRoute
  ReorderPdfPagesRoute: typeof ReorderPdfPagesRoute
  RepairPdfRoute: typeof RepairPdfRoute
  ResizePdfRoute: typeof ResizePdfRoute
  ReversePdfRoute: typeof ReversePdfRoute
  RotatePdfRoute: typeof RotatePdfRoute
  SecurePdfRoute: typeof SecurePdfRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SplitPdfRoute: typeof SplitPdfRoute
  TermsRoute: typeof TermsRoute
  UnlockPdfRoute: typeof UnlockPdfRoute
  WatermarkPdfRoute: typeof WatermarkPdfRoute
  WordToPdfRoute: typeof WordToPdfRoute
  ConvertSlugRoute: typeof ConvertSlugRoute
  ToolsSlugRoute: typeof ToolsSlugRoute
  UseCasesSlugRoute: typeof UseCasesSlugRoute
  VsSlugRoute: typeof VsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/word-to-pdf': {
      id: '/word-to-pdf'
      path: '/word-to-pdf'
      fullPath: '/word-to-pdf'
      preLoaderRoute: typeof WordToPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watermark-pdf': {
      id: '/watermark-pdf'
      path: '/watermark-pdf'
      fullPath: '/watermark-pdf'
      preLoaderRoute: typeof WatermarkPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unlock-pdf': {
      id: '/unlock-pdf'
      path: '/unlock-pdf'
      fullPath: '/unlock-pdf'
      preLoaderRoute: typeof UnlockPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/split-pdf': {
      id: '/split-pdf'
      path: '/split-pdf'
      fullPath: '/split-pdf'
      preLoaderRoute: typeof SplitPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/secure-pdf': {
      id: '/secure-pdf'
      path: '/secure-pdf'
      fullPath: '/secure-pdf'
      preLoaderRoute: typeof SecurePdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rotate-pdf': {
      id: '/rotate-pdf'
      path: '/rotate-pdf'
      fullPath: '/rotate-pdf'
      preLoaderRoute: typeof RotatePdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reverse-pdf': {
      id: '/reverse-pdf'
      path: '/reverse-pdf'
      fullPath: '/reverse-pdf'
      preLoaderRoute: typeof ReversePdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resize-pdf': {
      id: '/resize-pdf'
      path: '/resize-pdf'
      fullPath: '/resize-pdf'
      preLoaderRoute: typeof ResizePdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repair-pdf': {
      id: '/repair-pdf'
      path: '/repair-pdf'
      fullPath: '/repair-pdf'
      preLoaderRoute: typeof RepairPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reorder-pdf-pages': {
      id: '/reorder-pdf-pages'
      path: '/reorder-pdf-pages'
      fullPath: '/reorder-pdf-pages'
      preLoaderRoute: typeof ReorderPdfPagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redact-pdf': {
      id: '/redact-pdf'
      path: '/redact-pdf'
      fullPath: '/redact-pdf'
      preLoaderRoute: typeof RedactPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protect-pdf': {
      id: '/protect-pdf'
      path: '/protect-pdf'
      fullPath: '/protect-pdf'
      preLoaderRoute: typeof ProtectPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdf-to-word': {
      id: '/pdf-to-word'
      path: '/pdf-to-word'
      fullPath: '/pdf-to-word'
      preLoaderRoute: typeof PdfToWordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdf-to-ppt': {
      id: '/pdf-to-ppt'
      path: '/pdf-to-ppt'
      fullPath: '/pdf-to-ppt'
      preLoaderRoute: typeof PdfToPptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdf-to-png': {
      id: '/pdf-to-png'
      path: '/pdf-to-png'
      fullPath: '/pdf-to-png'
      preLoaderRoute: typeof PdfToPngRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdf-to-pdfa': {
      id: '/pdf-to-pdfa'
      path: '/pdf-to-pdfa'
      fullPath: '/pdf-to-pdfa'
      preLoaderRoute: typeof PdfToPdfaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdf-to-jpg': {
      id: '/pdf-to-jpg'
      path: '/pdf-to-jpg'
      fullPath: '/pdf-to-jpg'
      preLoaderRoute: typeof PdfToJpgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdf-to-excel': {
      id: '/pdf-to-excel'
      path: '/pdf-to-excel'
      fullPath: '/pdf-to-excel'
      preLoaderRoute: typeof PdfToExcelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organize-pdf': {
      id: '/organize-pdf'
      path: '/organize-pdf'
      fullPath: '/organize-pdf'
      preLoaderRoute: typeof OrganizePdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ocr-pdf': {
      id: '/ocr-pdf'
      path: '/ocr-pdf'
      fullPath: '/ocr-pdf'
      preLoaderRoute: typeof OcrPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/n-up-pdf': {
      id: '/n-up-pdf'
      path: '/n-up-pdf'
      fullPath: '/n-up-pdf'
      preLoaderRoute: typeof NUpPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merge-pdf': {
      id: '/merge-pdf'
      path: '/merge-pdf'
      fullPath: '/merge-pdf'
      preLoaderRoute: typeof MergePdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms-full.txt': {
      id: '/llms-full.txt'
      path: '/llms-full.txt'
      fullPath: '/llms-full.txt'
      preLoaderRoute: typeof LlmsFullDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jpg-to-pdf': {
      id: '/jpg-to-pdf'
      path: '/jpg-to-pdf'
      fullPath: '/jpg-to-pdf'
      preLoaderRoute: typeof JpgToPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invert-pdf': {
      id: '/invert-pdf'
      path: '/invert-pdf'
      fullPath: '/invert-pdf'
      preLoaderRoute: typeof InvertPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/html-to-pdf': {
      id: '/html-to-pdf'
      path: '/html-to-pdf'
      fullPath: '/html-to-pdf'
      preLoaderRoute: typeof HtmlToPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grayscale-pdf': {
      id: '/grayscale-pdf'
      path: '/grayscale-pdf'
      fullPath: '/grayscale-pdf'
      preLoaderRoute: typeof GrayscalePdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flatten-pdf': {
      id: '/flatten-pdf'
      path: '/flatten-pdf'
      fullPath: '/flatten-pdf'
      preLoaderRoute: typeof FlattenPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extract-text-pdf': {
      id: '/extract-text-pdf'
      path: '/extract-text-pdf'
      fullPath: '/extract-text-pdf'
      preLoaderRoute: typeof ExtractTextPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extract-pdf-pages': {
      id: '/extract-pdf-pages'
      path: '/extract-pdf-pages'
      fullPath: '/extract-pdf-pages'
      preLoaderRoute: typeof ExtractPdfPagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extract-images-pdf': {
      id: '/extract-images-pdf'
      path: '/extract-images-pdf'
      fullPath: '/extract-images-pdf'
      preLoaderRoute: typeof ExtractImagesPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/excel-to-pdf': {
      id: '/excel-to-pdf'
      path: '/excel-to-pdf'
      fullPath: '/excel-to-pdf'
      preLoaderRoute: typeof ExcelToPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esign-pdf': {
      id: '/esign-pdf'
      path: '/esign-pdf'
      fullPath: '/esign-pdf'
      preLoaderRoute: typeof EsignPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit-pdf': {
      id: '/edit-pdf'
      path: '/edit-pdf'
      fullPath: '/edit-pdf'
      preLoaderRoute: typeof EditPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit-metadata-pdf': {
      id: '/edit-metadata-pdf'
      path: '/edit-metadata-pdf'
      fullPath: '/edit-metadata-pdf'
      preLoaderRoute: typeof EditMetadataPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/duplicate-pages-pdf': {
      id: '/duplicate-pages-pdf'
      path: '/duplicate-pages-pdf'
      fullPath: '/duplicate-pages-pdf'
      preLoaderRoute: typeof DuplicatePagesPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delete-pdf-pages': {
      id: '/delete-pdf-pages'
      path: '/delete-pdf-pages'
      fullPath: '/delete-pdf-pages'
      preLoaderRoute: typeof DeletePdfPagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crop-pdf': {
      id: '/crop-pdf'
      path: '/crop-pdf'
      fullPath: '/crop-pdf'
      preLoaderRoute: typeof CropPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convert-pdf': {
      id: '/convert-pdf'
      path: '/convert-pdf'
      fullPath: '/convert-pdf'
      preLoaderRoute: typeof ConvertPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compress-pdf': {
      id: '/compress-pdf'
      path: '/compress-pdf'
      fullPath: '/compress-pdf'
      preLoaderRoute: typeof CompressPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare-pdf': {
      id: '/compare-pdf'
      path: '/compare-pdf'
      fullPath: '/compare-pdf'
      preLoaderRoute: typeof ComparePdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blank-page-pdf': {
      id: '/blank-page-pdf'
      path: '/blank-page-pdf'
      fullPath: '/blank-page-pdf'
      preLoaderRoute: typeof BlankPagePdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/base64-pdf': {
      id: '/base64-pdf'
      path: '/base64-pdf'
      fullPath: '/base64-pdf'
      preLoaderRoute: typeof Base64PdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai.txt': {
      id: '/ai.txt'
      path: '/ai.txt'
      fullPath: '/ai.txt'
      preLoaderRoute: typeof AiDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-watermark-text-pdf': {
      id: '/add-watermark-text-pdf'
      path: '/add-watermark-text-pdf'
      fullPath: '/add-watermark-text-pdf'
      preLoaderRoute: typeof AddWatermarkTextPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-page-numbers-pdf': {
      id: '/add-page-numbers-pdf'
      path: '/add-page-numbers-pdf'
      fullPath: '/add-page-numbers-pdf'
      preLoaderRoute: typeof AddPageNumbersPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vs/$slug': {
      id: '/vs/$slug'
      path: '/vs/$slug'
      fullPath: '/vs/$slug'
      preLoaderRoute: typeof VsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-cases/$slug': {
      id: '/use-cases/$slug'
      path: '/use-cases/$slug'
      fullPath: '/use-cases/$slug'
      preLoaderRoute: typeof UseCasesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/$slug': {
      id: '/tools/$slug'
      path: '/tools/$slug'
      fullPath: '/tools/$slug'
      preLoaderRoute: typeof ToolsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convert/$slug': {
      id: '/convert/$slug'
      path: '/convert/$slug'
      fullPath: '/convert/$slug'
      preLoaderRoute: typeof ConvertSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/_authenticated/cp-crisp-7x92k': {
      id: '/_authenticated/cp-crisp-7x92k'
      path: '/cp-crisp-7x92k'
      fullPath: '/cp-crisp-7x92k'
      preLoaderRoute: typeof AuthenticatedCpCrisp7x92kRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCpCrisp7x92kRoute: typeof AuthenticatedCpCrisp7x92kRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCpCrisp7x92kRoute: AuthenticatedCpCrisp7x92kRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AddPageNumbersPdfRoute: AddPageNumbersPdfRoute,
  AddWatermarkTextPdfRoute: AddWatermarkTextPdfRoute,
  AiDottxtRoute: AiDottxtRoute,
  AuthRoute: AuthRoute,
  Base64PdfRoute: Base64PdfRoute,
  BlankPagePdfRoute: BlankPagePdfRoute,
  BlogRoute: BlogRouteWithChildren,
  ChangelogRoute: ChangelogRoute,
  ComparePdfRoute: ComparePdfRoute,
  CompressPdfRoute: CompressPdfRoute,
  ContactRoute: ContactRoute,
  ConvertPdfRoute: ConvertPdfRoute,
  CropPdfRoute: CropPdfRoute,
  DeletePdfPagesRoute: DeletePdfPagesRoute,
  DuplicatePagesPdfRoute: DuplicatePagesPdfRoute,
  EditMetadataPdfRoute: EditMetadataPdfRoute,
  EditPdfRoute: EditPdfRoute,
  EsignPdfRoute: EsignPdfRoute,
  ExcelToPdfRoute: ExcelToPdfRoute,
  ExtractImagesPdfRoute: ExtractImagesPdfRoute,
  ExtractPdfPagesRoute: ExtractPdfPagesRoute,
  ExtractTextPdfRoute: ExtractTextPdfRoute,
  FlattenPdfRoute: FlattenPdfRoute,
  GrayscalePdfRoute: GrayscalePdfRoute,
  HtmlToPdfRoute: HtmlToPdfRoute,
  InvertPdfRoute: InvertPdfRoute,
  JpgToPdfRoute: JpgToPdfRoute,
  LlmsFullDottxtRoute: LlmsFullDottxtRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  MergePdfRoute: MergePdfRoute,
  NUpPdfRoute: NUpPdfRoute,
  OcrPdfRoute: OcrPdfRoute,
  OrganizePdfRoute: OrganizePdfRoute,
  PdfToExcelRoute: PdfToExcelRoute,
  PdfToJpgRoute: PdfToJpgRoute,
  PdfToPdfaRoute: PdfToPdfaRoute,
  PdfToPngRoute: PdfToPngRoute,
  PdfToPptRoute: PdfToPptRoute,
  PdfToWordRoute: PdfToWordRoute,
  PrivacyRoute: PrivacyRoute,
  ProtectPdfRoute: ProtectPdfRoute,
  RedactPdfRoute: RedactPdfRoute,
  ReorderPdfPagesRoute: ReorderPdfPagesRoute,
  RepairPdfRoute: RepairPdfRoute,
  ResizePdfRoute: ResizePdfRoute,
  ReversePdfRoute: ReversePdfRoute,
  RotatePdfRoute: RotatePdfRoute,
  SecurePdfRoute: SecurePdfRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SplitPdfRoute: SplitPdfRoute,
  TermsRoute: TermsRoute,
  UnlockPdfRoute: UnlockPdfRoute,
  WatermarkPdfRoute: WatermarkPdfRoute,
  WordToPdfRoute: WordToPdfRoute,
  ConvertSlugRoute: ConvertSlugRoute,
  ToolsSlugRoute: ToolsSlugRoute,
  UseCasesSlugRoute: UseCasesSlugRoute,
  VsSlugRoute: VsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
