INSERT INTO public.tool_settings (slug,name,enabled) VALUES
  ('merge-pdf', 'Merge PDF', true),
  ('split-pdf', 'Split PDF', true),
  ('compress-pdf', 'Compress PDF', true),
  ('pdf-to-word', 'PDF to Word', true),
  ('pdf-to-excel', 'PDF to Excel', true),
  ('pdf-to-ppt', 'PDF to PowerPoint', true),
  ('pdf-to-jpg', 'PDF to JPG', true),
  ('pdf-to-png', 'PDF to PNG', true),
  ('word-to-pdf', 'Word to PDF', true),
  ('excel-to-pdf', 'Excel to PDF', true),
  ('jpg-to-pdf', 'JPG to PDF', true),
  ('html-to-pdf', 'HTML to PDF', true),
  ('rotate-pdf', 'Rotate PDF', true),
  ('reorder-pdf-pages', 'Reorder Pages', true),
  ('delete-pdf-pages', 'Delete Pages', true),
  ('extract-pdf-pages', 'Extract Pages', true),
  ('crop-pdf', 'Crop PDF', true),
  ('repair-pdf', 'Repair PDF', true),
  ('flatten-pdf', 'Flatten PDF', true),
  ('pdf-to-pdfa', 'PDF to PDF/A', true),
  ('grayscale-pdf', 'Grayscale PDF', true),
  ('protect-pdf', 'Protect PDF', true),
  ('unlock-pdf', 'Unlock PDF', true),
  ('redact-pdf', 'Redact PDF', true),
  ('esign-pdf', 'eSign PDF', true),
  ('watermark-pdf', 'Watermark PDF', true),
  ('ocr-pdf', 'OCR PDF', true),
  ('add-page-numbers-pdf', 'Add Page Numbers', true),
  ('add-watermark-text-pdf', 'Add Watermark Text', true),
  ('extract-images-pdf', 'Extract Images', true),
  ('invert-pdf', 'Invert Colors PDF', true),
  ('resize-pdf', 'Resize PDF', true),
  ('n-up-pdf', 'N-up PDF', true),
  ('blank-page-pdf', 'Insert Blank Pages', true),
  ('duplicate-pages-pdf', 'Duplicate Pages', true),
  ('extract-text-pdf', 'Extract Text', true),
  ('edit-metadata-pdf', 'Edit PDF Metadata', true),
  ('compare-pdf', 'Compare PDFs', true),
  ('base64-pdf', 'PDF Base64', true),
  ('reverse-pdf', 'Reverse PDF', true)
ON CONFLICT (slug) DO UPDATE SET name=EXCLUDED.name;